version: "3.6"

services:
  api:
    image: infoambassador/dmt_api
    expose:
      - "5000"
    depends_on:
      - database
    environment:
      - FLASK_APP=run.py

  nginx:
    image: infoambassador/pmt_nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
      - client

  client:
    image: infoambassador/pmt_client_editor
    depends_on:
      - api
      - database
    environment:
      - REACT_APP_DEPLOYMENT_URL=http://deg-map.main.sjcd.edu

  database:
    image: infoambassador/pmt_database
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=Szw42elk!
    volumes:
      - my-datavolume:/var/lib/mysql

  pmt_reports:
    image: infoambassador/pmt_reports
    expose:
      - "80"
    environment:
      - REACT_APP_DEPLOYMENT_URL=http://deg-map.main.sjcd.edu

volumes:
  my-datavolume:
