version: '3.6'

services:

  api:
    build: 
      context: services/dmt_backend
      dockerfile: Dockerfile
    image: infoambassador/pmt_api
    expose:
      - '5000'
    depends_on:
      - database
    environment:
      - FLASK_APP=run.py
    volumes:
      - './services/dmt_backend:/api'

  nginx:
    build:
      context: services/pmt_nginx
      dockerfile: Dockerfile
    restart: always
    image: infoambassador/pmt_nginx
    ports:
      - 80:80
    depends_on:
      - api
      - client

  client:
    build:
      context: services/dmt_frontend
      dockerfile: Dockerfile
    image: infoambassador/pmt_client_editor
    depends_on:
      - api
      - database
    
  database:
    build:
      context: services/pmt_database
      dockerfile: Dockerfile
    image: infoambassador/pmt_database
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=Szw42elk!

  pmt_reports:
    build:
      context: services/pmt_reports
      dockerfile: Dockerfile
    image: infoambassador/pmt_reports
    expose:
      - '80'