version: '3.6'

services:

  api:
    build: 
      context: services/dmt_backend
      dockerfile: Dockerfile-dev
    expose:
      - '5000'
    depends_on:
      - database
    environment:
      - FLASK_APP=run.py
    volumes:
      - './services/dmt_backend:/api'

  nginx:
    build:
      context: services/pmt_nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
      - client

  client:
    build:
      context: services/dmt_frontend
      dockerfile: Dockerfile-dev
    depends_on:
      - api
      - database
    expose:
      - '3000'
    volumes:
      - './services/dmt_frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    
  database:
    build:
      context: services/pmt_database
      dockerfile: Dockerfile
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=Szw42elk!
    volumes:
      - my-datavolume:/var/lib/mysql

  pmt_reports:
    build:
      context: services/pmt_reports
      dockerfile: Dockerfile-dev
    expose:
      - '3000'
    volumes:
      - './services/pmt_reports:/usr/src/app'
      - '/usr/src/app/node_modules'

volumes:
  my-datavolume: