"""empty message

Revision ID: 1469df422ec6
Revises: b0e3f1a98b09
Create Date: 2018-03-30 12:33:55.336807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1469df422ec6'
down_revision = 'b0e3f1a98b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_name', sa.String(length=255)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.drop_column('map_name')

    # ### end Alembic commands ###
