"""empty message

Revision ID: 2352da22548c
Revises: c822e5117017
Create Date: 2018-03-24 08:25:09.930545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2352da22548c'
down_revision = 'c822e5117017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comm_010_1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comm_010_2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comp_090_1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comp_090_2', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('comp_SJC_1', 'SJC', ['comp_090_1'], ['id'])
        batch_op.create_foreign_key('comp_SJC_2', 'SJC', ['comm_010_1'], ['id'])
        batch_op.create_foreign_key('comp_SJC_3', 'SJC', ['comp_090_2'], ['id'])
        batch_op.create_foreign_key('comp_SJC_4', 'SJC', ['comm_010_2'], ['id'])
        batch_op.drop_column('comp_090')
        batch_op.drop_column('comm_101_2')
        batch_op.drop_column('comm_101_1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comm_101_1', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('comm_101_2', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('comp_090', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('comp_SJC_1', type_='foreignkey')
        batch_op.drop_constraint('comp_SJC_2', type_='foreignkey')
        batch_op.drop_constraint('comp_SJC_3', type_='foreignkey')
        batch_op.drop_constraint('comp_SJC_4', type_='foreignkey')
        batch_op.create_foreign_key('SJC_comp_1', 'SJC', ['comm_101_1'], ['id'])
        batch_op.create_foreign_key('SJC_comp_2', 'SJC', ['comm_101_2'], ['id'])
        batch_op.create_foreign_key('SJC_comp_3', 'SJC', ['comp_090'], ['id'])
        batch_op.drop_column('comp_090_2')
        batch_op.drop_column('comp_090_1')
        batch_op.drop_column('comm_010_2')
        batch_op.drop_column('comm_010_1')

    # ### end Alembic commands ###
