"""empty message

Revision ID: 36d83c2fb1e2
Revises: 1469df422ec6
Create Date: 2018-05-16 14:25:53.333898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d83c2fb1e2'
down_revision = '1469df422ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('univ_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.drop_column('univ_id')
    # ### end Alembic commands ###
