"""empty message

Revision ID: 6a90282e65e3
Revises: 1d5e429aabe6
Create Date: 2018-03-21 11:22:30.487274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a90282e65e3'
down_revision = '1d5e429aabe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comm_101_1', sa.Integer(), nullable=True),
    sa.Column('comm_101_2', sa.Integer(), nullable=True),
    sa.Column('math_020', sa.Integer(), nullable=True),
    sa.Column('sci_030_1', sa.Integer(), nullable=True),
    sa.Column('sci_030_2', sa.Integer(), nullable=True),
    sa.Column('phil_040', sa.Integer(), nullable=True),
    sa.Column('arts_050', sa.Integer(), nullable=True),
    sa.Column('hist_060_1', sa.Integer(), nullable=True),
    sa.Column('hist_060_2', sa.Integer(), nullable=True),
    sa.Column('gov_070_1', sa.Integer(), nullable=True),
    sa.Column('gov_070_2', sa.Integer(), nullable=True),
    sa.Column('soc_080', sa.Integer(), nullable=True),
    sa.Column('comp_090', sa.Integer(), nullable=True),
    sa.Column('trans_1', sa.Integer(), nullable=True),
    sa.Column('trans_2', sa.Integer(), nullable=True),
    sa.Column('trans_3', sa.Integer(), nullable=True),
    sa.Column('trans_4', sa.Integer(), nullable=True),
    sa.Column('trans_5', sa.Integer(), nullable=True),
    sa.Column('trans_6', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['arts_050'], ['SJC.id'], ),
    sa.ForeignKeyConstraint(['comm_101_1'], ['SJC.id'], ),
    sa.ForeignKeyConstraint(['comm_101_2'], ['SJC.id'], ),
    sa.ForeignKeyConstraint(['comp_090'], ['SJC.id'], ),
    sa.ForeignKeyConstraint(['gov_070_1'], ['SJC.id'], ),
    sa.ForeignKeyConstraint(['gov_070_2'], ['SJC.id'], ),
    sa.ForeignKeyConstraint(['hist_060_1'], ['SJC.id'], ),
    sa.ForeignKeyConstraint(['hist_060_2'], ['SJC.id'], ),
    sa.ForeignKeyConstraint(['math_020'], ['SJC.id'], ),
    sa.ForeignKeyConstraint(['phil_040'], ['SJC.id'], ),
    sa.ForeignKeyConstraint(['sci_030_1'], ['SJC.id'], ),
    sa.ForeignKeyConstraint(['sci_030_2'], ['SJC.id'], ),
    sa.ForeignKeyConstraint(['soc_080'], ['SJC.id'], ),
    sa.ForeignKeyConstraint(['trans_1'], ['SJC.id'], ),
    sa.ForeignKeyConstraint(['trans_2'], ['SJC.id'], ),
    sa.ForeignKeyConstraint(['trans_3'], ['SJC.id'], ),
    sa.ForeignKeyConstraint(['trans_4'], ['SJC.id'], ),
    sa.ForeignKeyConstraint(['trans_5'], ['SJC.id'], ),
    sa.ForeignKeyConstraint(['trans_6'], ['SJC.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map')
    # ### end Alembic commands ###
