"""empty message

Revision ID: 8cb21ce778f4
Revises: 32fab8c376bb
Create Date: 2018-05-21 15:47:44.622948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb21ce778f4'
down_revision = '32fab8c376bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trans_5', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('trans_6', sa.Integer(), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:

        batch_op.drop_column('trans_6')
        batch_op.drop_column('trans_5')

    # ### end Alembic commands ###
