"""empty message

Revision ID: 8c21ce778f4
Revises: 76e8bb6f997f
Create Date: 2018-03-21 11:12:21.492395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c21ce778f4'
down_revision = '76e8bb6f997f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SJC', schema=None) as batch_op:
        batch_op.create_foreign_key('SJC_at_UHCL', 'course', ['UHCL_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SJC', schema=None) as batch_op:
        batch_op.drop_constraint('SJC_at_UHCL', type_='foreignkey')

    # ### end Alembic commands ###