"""empty message

Revision ID: 96b53ec02390
Revises: 
Create Date: 2018-03-21 10:58:07.988066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b53ec02390'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ACGM', schema=None) as batch_op:
        batch_op.create_foreign_key('UHCL_in_ACGM', 'course', ['UHCL_id'], ['id'])
        batch_op.create_foreign_key('SJC_in_ACGM', 'SJC', ['SJC_id'], ['id'])

    with op.batch_alter_table('SJC', schema=None) as batch_op:
        batch_op.create_foreign_key('UHCL_at_SJC', 'course', ['UHCL_id'], ['id'])
        batch_op.create_foreign_key('UHCL_at_SJC', 'ACGM', ['ACGM_id'], ['id'])

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_foreign_key('univ_in_ACGM', 'ACGM', ['acgm_id'], ['id'])
        batch_op.create_foreign_key('univ_at_SJC', 'SJC', ['sjc_id'], ['id'])
        batch_op.create_foreign_key('prereq_info', 'course', ['super_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint('univ_in_ACGM', type_='foreignkey')
        batch_op.drop_constraint('univ_at_SJC', type_='foreignkey')
        batch_op.drop_constraint('prereq_info', type_='foreignkey')

    with op.batch_alter_table('SJC', schema=None) as batch_op:
        batch_op.drop_constraint('UHCL_at_SJC', type_='foreignkey')
        batch_op.drop_constraint('UHCL_at_SJC', type_='foreignkey')

    with op.batch_alter_table('ACGM', schema=None) as batch_op:
        batch_op.drop_constraint('UHCL_in_ACGM', type_='foreignkey')
        batch_op.drop_constraint('SJC_in_ACGM', type_='foreignkey')

    # ### end Alembic commands ###
