"""empty message

Revision ID: b0e3f1a98b09
Revises: 2352da22548c
Create Date: 2018-03-26 14:52:37.850144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e3f1a98b09'
down_revision = '2352da22548c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inst_opt_1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('inst_opt_2', sa.Integer(), nullable=True))

        batch_op.drop_column('trans_5')
        batch_op.drop_column('trans_6')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trans_6', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('trans_5', sa.INTEGER(), nullable=True))

        batch_op.drop_column('inst_opt_2')
        batch_op.drop_column('inst_opt_1')

    # ### end Alembic commands ###
