"""empty message

Revision ID: c822e5117017
Revises: 6a90282e65e3
Create Date: 2018-03-21 11:25:02.374389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c822e5117017'
down_revision = '6a90282e65e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prog_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('prog_for_map', 'program', ['prog_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.drop_constraint('prog_for_map', type_='foreignkey')
        batch_op.drop_column('prog_id')

    # ### end Alembic commands ###
