###########
# BUILDER #
###########

# base image
FROM node:10.4.1-alpine as BUILDER

# set working directory
WORKDIR /usr/src/app

# install app dependencies
ENV PATH /usr/src/app/node/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json
RUN npm install --silent
RUN npm install react-scripts@1.1.4 -g --silent

EXPOSE 3000

# create build
COPY . /usr/src/app
CMD ["npm","start"]
